version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    command: php artisan serve --host=0.0.0.0 --port=9000
    volumes:
      - ./src:/var/www
    ports:
      - 9000:9000
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - /home/laravel_app/src:/var/www
      - /home/laravel_app/nginx:/etc/nginx/conf.d
    depends_on:
      - app

  mysql:
    image: mysql:5.7
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
  node:
    image: node:20
    container_name: vite-dev
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    command: npm run dev
    ports:
      - "5173:5173"
volumes:
  dbdata:
