name: Deploy to EC2 via Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy project to EC2 via rsync
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@13.250.1.39 "mkdir -p ~/laravel-app"
          rsync -avz --exclude=node_modules --exclude=vendor ./ ubuntu@13.250.1.39:~/laravel-app

      - name: Build and run docker on EC2
        run: |
          ssh ubuntu@13.250.1.39 << 'EOF'
            cd ~/laravel-app
            docker compose down
            docker compose up --build -d
            docker exec laravel_app php artisan migrate --force
          EOF
